name: test_push

on:
  push:
  pull_request:

jobs:
  # Unit test application
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}
      - name: Run unit-tests
        run: ./gradlew test

  # Build application
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}
      - name: Build APK
        run: ./gradlew assembleRelease
      - name: Upload main app APK
        uses: actions/upload-artifact@v2
        with:
          name: yad-release.apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk
      - name: Upload delivery boy app APK
        uses: actions/upload-artifact@v2
        with:
          name: yaboy-release.apk
          path: yaddeliveryboy/build/outputs/apk/release/yaddeliveryboy-release-unsigned.apk
